{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.1.aar",
          "url": "ui-graphics-1.0.1.aar",
          "size": 1368858,
          "sha512": "1d5031038339dccd8a5d97cdbcbcc96ca52784c023b2e0f9766ebebbbdbb9a3a9e5a6c5fac142b0ae7df1e9ffb866d8cf0a120f49c24bf7a0393dd16a99ce894",
          "sha256": "6b7f5d0c944483ea390b3d6da8438e7a69e0cfe310bd16c3c5e78ac0015b1663",
          "sha1": "00061c9307247494229658e61969f797da27d74e",
          "md5": "ed5ca52d9dfb7fcdb77ca0187fe720a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.0.1.aar",
          "url": "ui-graphics-1.0.1.aar",
          "size": 1368858,
          "sha512": "1d5031038339dccd8a5d97cdbcbcc96ca52784c023b2e0f9766ebebbbdbb9a3a9e5a6c5fac142b0ae7df1e9ffb866d8cf0a120f49c24bf7a0393dd16a99ce894",
          "sha256": "6b7f5d0c944483ea390b3d6da8438e7a69e0cfe310bd16c3c5e78ac0015b1663",
          "sha1": "00061c9307247494229658e61969f797da27d74e",
          "md5": "ed5ca52d9dfb7fcdb77ca0187fe720a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.0.1-sources.jar",
          "url": "ui-graphics-1.0.1-sources.jar",
          "size": 152723,
          "sha512": "a12b1b8d7daae1d03fa1938f0ce681f398b26d3dc69dfb33d4725f4bf023b05f144137dbb1a87070a1306f1bd61aac466d90dfb4ed1a5755db92a2ba677684b5",
          "sha256": "1e1387f756868e14dd848c00dc0c9783b594c6a047eae13a08fd36f254748fad",
          "sha1": "99e2112f5a1a0c64eff13c5543ba1bf1a9a3c3a3",
          "md5": "6e22d60f52fcff97761038049b370d45"
        }
      ]
    }
  ]
}
